micronaut:
  application:
    name: mnExternalClientCamunda
  server:
    port: 8088
camunda.external-client.base-url: http://localhost:8080/engine-rest
netty:
  default:
    allocator:
      max-order: 3
